name: ci
on: [push]
jobs:
  test:
    # use the reusable workflow to check out the code, install dependencies
    # and run the Cypress tests
    # https://github.com/bahmutov/cypress-workflows
    uses: bahmutov/cypress-workflows/.github/workflows/standard.yml@v1
    with:
      start: 'npm run dev'
      wait-on: 'http://localhost:3000'
      wait-on-timeout: 60
      record: true
    secrets:
      recordKey: ${{ secrets.CYPRESS_RECORD_KEY }}
